# syntax=docker/dockerfile:1.4
FROM ubuntu:24.04 AS base

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8


RUN apt-get update \
    && apt-get install -fy -qq --no-install-recommends \
    ca-certificates curl jq unzip locales \
    ca-certificates-java default-jre-headless openjdk-21-jre-headless \
    && apt-get clean

RUN locale-gen en_US.UTF-8

RUN curl -sLo allure_2.30.0-1_all.deb https://github.com/allure-framework/allure2/releases/download/2.30.0/allure_2.30.0-1_all.deb
RUN dpkg -i allure_2.30.0-1_all.deb

#RUN curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
#RUN unzip -q awscliv2.zip

ENTRYPOINT ["allure", "serve", "/allure-results", "--port", "8080", "--host", "0.0.0.0"]
